Models/ErrorViewModel.cs
namespace dotnet_mvc_crud.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/StudentModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace dotnet_mvc_crud.Models
{
    public class StudentModel
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "กรุณากรอกชื่อนักเรียน")]
        [DisplayName("ชื่อนักเรียน")]
        public string Name { get; set; }

        [Range(0, 100, ErrorMessage = "กรุณาป้อนคะแนนสอบระหว่าง 0-100")]
        [DisplayName("คะแนนสอบ")]
        public int Score { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using dotnet_mvc_crud.Models;

namespace dotnet_mvc_crud.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using dotnet_mvc_crud.Data;
using dotnet_mvc_crud.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace dotnet_mvc_crud.Controllers
{
    // [Route("[controller]")]
    public class StudentController : Controller
    {
        private readonly ApplicationDBContext _db;

        public StudentController(ApplicationDBContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            // StudentModel s1 = new StudentModel();
            // s1.Id = 1;
            // s1.Name = "Tony Stark";
            // s1.Score = 100;

            // var s2 = new StudentModel();
            // s2.Id = 2;
            // s2.Name = "Steve Rogers";
            // s2.Score = 45;

            // StudentModel s3 = new();
            // s3.Id = 1;
            // s3.Name = "Thor";
            // s3.Score = 70;

            // List<StudentModel> student = new List<StudentModel>();
            // student.Add(s1);
            // student.Add(s2);
            // student.Add(s3);

            // return View(student);
            IEnumerable<StudentModel> student = _db.Students;
            return View(student);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StudentModel data)
        {
            if (ModelState.IsValid)
            {
                _db.Students.Add(data);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(data);
        }

        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var data = _db.Students.Find(id);

            if (data == null)
            {
                return NotFound();
            }

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(StudentModel data)
        {
            if (ModelState.IsValid)
            {
                _db.Students.Update(data);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(data);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var data = _db.Students.Find(id);

            if (data == null)
            {
                return NotFound();
            }

            _db.Students.Remove(data);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/dotnet_mvc_crud.styles.css" asp-append-version="true" /> *@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Student" asp-action="Index">@ViewData["Title"]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Student" asp-action="Index">หน้าแรก</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Student" asp-action="Create">บันทึกข้อมูล</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2566 - @ViewData["Title"]
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Create.cshtml
@model StudentModel;
@{
    ViewData["Title"] = "บันทึกคะแนนสอบนักเรียน";
}

<div>
    <h1 class="text-center">@ViewData["Title"]</h1>
    <form asp-controller="Student" asp-action="Create" method="POST">
        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" type="text" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Score"></label>
            <input asp-for="Score" type="number" class="form-control" />
            <span asp-validation-for="Score" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary my-2">บันทึก</button>
    </form>
</div>

Views/Student/Index.cshtml
@model IEnumerable<dotnet_mvc_crud.Models.StudentModel>;
@{
    ViewData["Title"] = "คะแนนสอบวิชาคอมพิวเตอร์";
}

<div>
    <h1 class="text-center">@ViewData["Title"]</h1>

    <table class="table table-bordered table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th>รหัสนักเรียน</th>
                <th>ชื่อ</th>
                <th>คะแนนสอบ</th>
                <th>สถานะ</th>
                <th>ดำเนินการ</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {
                @foreach (var data in Model)
                {
                    <tr>
                        <td>@data.Id</td>
                        <td>@data.Name</td>
                        <td>@data.Score</td>
                        <td>
                            @if (@data.Score >= 50)
                            {
                                <strong class="text-success">สอบผ่าน</strong>
                            }
                            else
                            {
                                <strong class="text-danger">สอบไม่ผ่าน</strong>
                            }
                        </td>
                        <td>
                            <a asp-controller="Student" asp-action="Update" asp-route-id="@data.Id" type="button"
                                class="btn btn-sm btn-warning">แก้ไข</a>
                            <a asp-controller="Student" asp-action="Delete" asp-route-id="@data.Id"
                                onclick="return confirm('คุณต้องการลบ @data.Name ใช่หรือไม่ ?')" type="button"
                                class="btn btn-sm btn-danger">ลบ</a>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="5" class="text-center">ไม่มีข้อมูลในระบบ</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Student/Update.cshtml
@model StudentModel;
@{
    ViewData["Title"] = "แก้ไขคะแนนสอบนักเรียน";
}

<div>
    <h1 class="text-center">@ViewData["Title"]</h1>
    <form asp-controller="Student" asp-action="Update" method="POST">
        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" type="text" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Score"></label>
            <input asp-for="Score" type="number" class="form-control" />
            <span asp-validation-for="Score" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary my-2">แก้ไข</button>
    </form>
</div>